### ISSUE TITLE
Page Info / Security is empty

### ISSUE THREAD

**Issue by schmi43** [AddonLab/AiOS#93]
Firefox 42 with AiOS 0.7.27: With AiOS enabled all information on the security page is missing. I have to disable AiOS to see certificates or details about the site's encryption.

**Comment by jimromaine** [comment]
I see the same.  I am also missing the information on the General tab as well.  

![capture](https://cloud.githubusercontent.com/assets/11447118/10998191/7285a810-8461-11e5-8c2a-5eda690940a0.PNG)

**Comment by vobexo** [comment]
Same Issue


![https](https://cloud.githubusercontent.com/assets/15708369/11017289/82b5fa98-859a-11e5-80b2-477c4761beac.jpg)

**Comment by Jan02** [comment]
confirmed with windows 7 too, had to disable the extension for now.

**Comment by JeffByers** [comment]
No need to disable the extension, you can still get to the native Firefox Page Info using menu Tools -> Page Info.Unfortunately since the keyboard accelerators Alt+T+I brings up the AiOS Info sidebar, and the Ctrl+Shift+P keyboard shortcut doesn't work at all, you have to use Alt to see the menu bar, and then the mouse. Not nearly as nice as the AiOS Info side page though.

**Comment by brand404** [comment]
@Jeff when u manually mouse to tools > Page Info that still brings up AiOS.  My only solution is to disable it :(

**Comment by JeffByers** [comment]
@brand404 Yes, you are of course correct. When I was testing this, I must have had the AIOS plug-in turned off. I found this out myself this morning to my disappointment when I needed the Page Info. Sorry for the false hope. It will be nice when this AIOS issue is fixed.

**Comment by RDL-github** [comment]
Have you tried clicking the AiOS "i" (for information) button while holding down the shift key? For me, that opens page information in a new window and all the information is then present.

The modifier key may be different for you if you have changed it.

**Comment by jimromaine** [comment]
@RDL-github Yes, that's the standard FF window.  You see the same window if you go to Tool>Page Info.  It's an ok band-aid if you don't want to disable AiOS, but the issue still needs to be addressed.

**Comment by norstbox** [comment]
**Temporary workaround**:
1. Unpack extension `{097d3191-e6fa-4728-9826-b533d755359d}.xpi` using your favorite archiver (7-Zip for example) to `{097d3191-e6fa-4728-9826-b533d755359d}` directory.
2. Delete file `pageinfo.xul` in `content` subdirectory of unpacked extension.
3. Delete file `{097d3191-e6fa-4728-9826-b533d755359d}.xpi`
4. Set `extensions.aios.pi.sidebar` to `false`

**Comment by RDL-github** [comment]
@jimromaine

"@RDL-github Yes, that's the standard FF window. You see the same window if you go to Tool>Page Info."

Thank you. Actually I don't see it if I go to 'Tools'>'Page Info'. I see the sidebar and I got the impression some others also did.

"It's an ok band-aid if you don't want to disable AiOS, but the issue still needs to be addressed."

Of course; I'd call it a "circumvention" (way round) and I only posted it to help anyone who had a totally blank display see at least most of it without having to disable AiOS until a fix appears.

However:

"I see the general page info, but I don't see the Security info."

I see _everything _except_ the security information and that, of course, I must admit, is what this thread is about. Sorry. I should have posted my circumvention in topic ' aios not compatible with "page info" #94'

**Comment by ptar** [comment]
Since this issue concerns the security information, the only save "workaround" is to disable AIOS.

Is there a real fix on the way? Would be great, to get AIOS back ASAP!

**Comment by norstbox** [comment]
@ptar @jimromaine 
>Since this issue concerns the security information, the only save "workaround" is to disable AIOS
Not quite. I [posted](https://github.com/AddonLab/AiOS/issues/93#issuecomment-157264043) "safe" workaround (so you can see "Security info") a few weeks ago.

**Comment by ptar** [comment]
You're right, so I have to add: There are no code changes for 2 months, now. If the solution is really easy for a developer, it should be fixed and released.
I gave an IMHO appropriate amount to the author, when he asked for it a few weeks ago.
But now it seems, the project is dead. :-(

**Comment by ingowennemaring** [comment]
Thanks for all the reports and excuse me for the long time silence on this. The project is not dead and I will work on a solution. :-)

**Comment by blausand** [comment]
Thanks, Ingo. Nice to hear this.
Tip: You might want to direct to AiOS issues on github from your homepage, since finding and hopping through the closed forum is for sure keeping tons of people from helping.

**Comment by ingowennemaring** [comment]
Hi all! 

Unfortunately there is no fast fix for this issue, but because I wanted to fix at least a part of this issue I just released 0.7.28. The page info is now working if opened in the default window, which now also is the default setting for this panel. 

Of course I will work for a complete solution.

**Comment by vobexo** [comment]
Hi ingowennemaring,
good job!
The security fix works for me, now i can see the securiti information and the Certificat.

thx a lot!

![aios](https://cloud.githubusercontent.com/assets/15708369/12130434/850323c2-b40a-11e5-84d9-61eaa67a7d00.jpg)

**Comment by RDL-github** [comment]
Please see my post today in topic 'aios not compatible with "page info" #94'

**Comment by vobexo** [comment]
Hi,
page info is working for me with AiOS 0.7.29

I will try 0.7.30

**Comment by kconover** [comment]
Still not working for me in 0.7.31; just tried it to check a saved PW, no luck. Works when click in the i-in-a-circle on the address bar. Win10 current update, FF49.0.2

**Comment by amiga-500** [comment]
Yup same here...not working (Win7 ult x64 - FF49.0.2).  Hasn't worked for some time (months).  I now just right-click on a page and click "_View Page Info_" as the only solution.

~Kimberly

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php
